### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ir-fuel** [magiclen/node-crc#2]
On my computer it installs fine, but on my Amazon Linux instance it gives an error

```
137 verbose stack Error: node-crc@1.2.2 install: `node-gyp rebuild`
137 verbose stack Exit status 1
137 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecyc$
137 verbose stack     at EventEmitter.emit (events.js:189:13)
137 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecyc$
137 verbose stack     at ChildProcess.emit (events.js:189:13)
137 verbose stack     at maybeClose (internal/child_process.js:970:16)
137 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
138 verbose pkgid node-crc@1.2.2
139 verbose cwd /home/ec2-user/XXXX
140 verbose Linux 4.14.109-80.92.amzn1.x86_64
141 verbose argv "/home/ec2-user/.nvm/versions/node/v10.15.3/bin/node" "/home/ec2-user/.nvm/versions/node/v10.15.3/bin/npm" "install"
142 verbose node v10.15.3
143 verbose npm  v6.4.1
144 error code ELIFECYCLE
145 error errno 1
146 error node-crc@1.2.2 install: `node-gyp rebuild`
146 error Exit status 1
147 error Failed at the node-crc@1.2.2 install script.
147 error This is probably not a problem with npm. There is likely additional logging output above.
148 verbose exit [ 1, true ]
```

**Comment by ir-fuel** [comment]
Fixed by running
```
sudo yum install gcc72 gcc72-c++
```
